### ISSUE TITLE
Support toolchains that run on Linux AARCH64

### ISSUE THREAD

**Issue by fhunleth** [nerves-project/toolchains#103]
This would allow people with 64-bit ARM Linux machines to build natively. While we currently distribute toolchains for Apple M1 users, this would also allow them to build inside Docker.

**Comment by fhunleth** [comment]
It turns out that this "just works". All that is needed is for someone to hook up CI to build them on AARCH64 machines. It looks like CircleCI supports this.

**Comment by fhunleth** [comment]
I uploaded toolchains that I built for AARCH64 under Docker on an M1. This is currently only for the 1.5.0 release. Since this is not in CI, it's not sustainable yet, but it would be interesting to know that they worked.

**Comment by jjcarstens** [comment]
I believe this has been resolved. Can you confirm?

**Comment by fhunleth** [comment]
Yes. We still need CI support since this is a manual build now.
