### ISSUE TITLE
Name toolchains 'nerves' rather than 'unknown'

### ISSUE THREAD

**Issue by fhunleth** [nerves-project/toolchains#15]
All of the toolchains are currently named `<arch>_unknown_linux_<abi>`. This is consistent with a lot of toolchains across the web, but doesn't indicate that we're the maintainers of them. Let's consider changing the `unknown` to `nerves`. 

The ramifications of doing this is that we need to create new hex packages and update every Nerves system with the change. The system updates aren't particularly painful since the old version will continue to exist.

**Comment by mobileoverlord** [comment]
This is fixed in v1.4.0
