### ISSUE TITLE
aarch64 toolchain name is incorrect

### ISSUE THREAD

**Issue by Zikoel** [nerves-project/toolchains#38]
### Environment

* Elixir version (`elixir -v`): not necessary
* Nerves environment: not necessary

### Current behavior
Inside the shell opened by `mix nerves.system.shell` and `make`
```
>>> toolchain-external-custom  Patching
>>> toolchain-external-custom  Configuring
Cannot execute cross-compiler '/home/.../custom_system/.nerves/artifacts/custom_system-portable-1.6.3/host/opt/ext-toolchain/bin/aarch64-unknown-linux-gnueabi-gcc'
package/pkg-generic.mk:219: recipe for target '/home/.../custom_system/.nerves/artifacts/custom_system-portable-1.6.3/build/toolchain-external-custom/.stamp_configured' failed
make[1]: *** [/home/.../custom_system/.nerves/artifacts/custom_system-portable-1.6.3/build/toolchain-external-custom/.stamp_configured] Error 1
Makefile:23: recipe for target '_all' failed
make: *** [_all] Error 2
```

### Expected behavior
No errors when using the cross compiler

### Notes
Seems that some toolchains have broken folder name `nerves_toolchain_aarch64_unknown_linux_gnu` instead of `nerves_toolchain_aarch64_unknown_linux_gnueabi` after renaming the bins mentioned in the error section all work ok! So... the problem is very simple I think but I am not sure if only rename the folder is sufficient to solve the problem so instead of open a pull-request I open this issue.

**Comment by fhunleth** [comment]
Thanks for reporting this. I ended up fixing it last week in https://github.com/nerves-project/toolchains/commit/5cb0e720008cb5a5daa0f042b9e85945a3926046, but timed out in making a new release.

I'm going to try to allocate some time next week to fix, but there was a regression in Crosstool-NG that may delay it. I may also give up and just make a patch release to get passed this.

Also, we don't have any official ARM64 systems. It might be time for us to start thinking about making one. What board are you using?

**Comment by Zikoel** [comment]
I'm working on a Orange Pi Zero Plus 2 I started the project from the official (working for me) [build root defconfig](https://raw.githubusercontent.com/buildroot/buildroot/master/configs/orangepi_zero_plus2_defconfig)

**Comment by Zikoel** [comment]
@fhunleth I know that you are working on it, just for remember to you! The versions
* `nerves_toolchain_aarch64_unknown_linux_gnueabi` -> `1.1.0`
* `nerves_toolchain_aarch64_unknown_linux_gnu` -> `1.2.0-rc.0`
have the same problems with the binary name inside the package! I can provide more details if needed. What I don't understand is what is the right name `linux_gnueabi` or `linux_gnu` ?

**Comment by fhunleth** [comment]
I'm able to build a 64-bit Raspberry Pi image. Could you double check your `defconfig`? Here are my settings:

```
BR2_TOOLCHAIN_EXTERNAL=y
BR2_TOOLCHAIN_EXTERNAL_CUSTOM=y
BR2_TOOLCHAIN_EXTERNAL_DOWNLOAD=y
BR2_TOOLCHAIN_EXTERNAL_URL="https://github.com/nerves-project/toolchains/releases/download/v1.2.0-rc.0/nerves_toolchain_aarch64_unknown_linux_gnu-linux_x86_64-1.2.0-rc.0-BEDC8BF.tar.xz"
BR2_TOOLCHAIN_EXTERNAL_CUSTOM_PREFIX="$(ARCH)-unknown-linux-gnu"
BR2_TOOLCHAIN_EXTERNAL_GCC_8=y
BR2_TOOLCHAIN_EXTERNAL_HEADERS_4_4=y
BR2_TOOLCHAIN_EXTERNAL_CUSTOM_GLIBC=y
BR2_TOOLCHAIN_EXTERNAL_CXX=y
```

You may also need to build clean. Maybe there's something stale in your build.

**Comment by Zikoel** [comment]
Thank you, I'll try asap (now I'm stuck on another problem relater to the kernel version) my mistake was that I only update the toolchain on the `mix.exs` but the one used the one inside the `defconfig` (so... why I need the toolchain dependency inside the `mix.exs` ?)

**Comment by fhunleth** [comment]
All dependencies in Elixir are brought in via `mix.exs` so since the toolchain is a dependency for building all C code in Elixir projects, it needs to be listed there. The `defconfig` is for Buildroot.

**Comment by Zikoel** [comment]
Thank you! I can confirm that the new version is working! In the next days I try to setup my circleci. Our trying to build the nervers system is [here](https://github.com/Zikoel/nerves_system_opzp2)

**Comment by fhunleth** [comment]
Great! Thanks for confirming.
