### ISSUE TITLE
Improve architecture naming

### ISSUE THREAD

**Issue by fhunleth** [nerves-project/toolchains#61]
The arm toolchain name here is the worst offender. It compiles for ARM v7 cores, but it's just called "arm". 

If we get an opportunity to rename toolchains, fixing the ARM toolchain's name and any others would be good. The Bootlin toolchains at https://toolchains.bootlin.com/ have pretty good names and consistency with them would be nice.

**Comment by mobileoverlord** [comment]
Toolchain names have been adjusted in release v1.4.0
